name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH agent and add key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copy files to VM using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" scp -r -o StrictHostKeyChecking=no * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~/backend

      - name: Check if Dockerfile was changed
        id: dockerfile_changed
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'Dockerfile'; then
            echo "Dockerfile was changed"
            echo "build_required=true" >> $GITHUB_ENV
          else
            echo "Dockerfil was not changed"
            echo "build_required=false" >> $GITHUB_ENV
          fi

      - name: Build docker image using password
        if: env.build_required == 'true'
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/backend
            docker-compose build
          EOF

      - name: Execute deployment commands on VM using password
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ~/backend
            docker-compose down
            docker-compose up -d
          EOF
